// Display Jay Ganesh on console n times where take the n value form the user

#include<stdio.h>

void Display(int iValue)
{
    int iCnt = 0 ;

    for(iCnt = 1 ; iCnt <= iValue ; iCnt++)
    {
        printf("Jay Ganesh... \n");
    }
}

int main()
{
    int iFrequency = 0 ;

    printf("Enter the frequency : \n");
    scanf("%d",&iFrequency);

    Display(iFrequency);

    return 0 ;
}

/* 
    OUTPUT

    Enter the frequency :
    5
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...


    Enter the frequency :
    15
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...


    Enter the frequency :
    1
    Jay Ganesh...

*/