// Display Jay Ganesh on console n times where take the n value form the user

#include<stdio.h>

int main()
{
    int iFrequency = 0 , iCnt = 0 ;

    printf("Enter the Frequency : \n ");
    scanf("%d",&iFrequency);

    for(iCnt = 1 ; iCnt <= iFrequency ; iCnt++)
    {
        printf("Jay Ganesh... \n");
    }

    return 0 ;
}

/*
    OUTPUT

    Enter the Frequency :
    2
    Jay Ganesh...
    Jay Ganesh...


    Enter the Frequency :
    5
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...


    Enter the Frequency :
    7
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...


    Enter the Frequency :
    20
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...
    Jay Ganesh...

*/